#!/usr/bin/env bash
# Create ansible-vault encrypted group_vars/application/vault.yml.
# Vault password is entered manually on this control PC (no .vault_pass written).
# Idempotent: refuses to overwrite existing vault.yml unless --force.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
VAULT_DIR="$ROOT/inventories/home-lab/group_vars/application"
VAULT_YML="$VAULT_DIR/vault.yml"
FORCE=0

if [[ "${1:-}" == "--force" ]]; then
  FORCE=1
fi

mkdir -p "$VAULT_DIR"

if [[ -f "$VAULT_YML" && "$FORCE" -ne 1 ]]; then
  echo "ERROR: $VAULT_YML already exists (pass --force to recreate)" >&2
  exit 1
fi

if ! command -v ansible-vault >/dev/null 2>&1; then
  echo "ERROR: ansible-vault not found on PATH" >&2
  exit 1
fi

if [[ ! -t 0 ]]; then
  echo "ERROR: interactive TTY required — vault password must be typed on this local PC" >&2
  exit 1
fi

ENC_KEY="$(openssl rand -base64 32)"

umask 077
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT
cat >"$TMP" <<EOF
---
# Generated by ansible/scripts/init-encryption-vault.sh
# Unlock later with: ansible-playbook ... --ask-vault-pass
k3s_secrets_encryption_key: "${ENC_KEY}"
EOF

# ansible-vault prompts twice for New Vault password (manual unlock secret).
ansible-vault encrypt "$TMP" --output "$VAULT_YML"
chmod 600 "$VAULT_YML"

# Prefer not leaving an auto-unlock password file around.
if [[ -f "$ROOT/.vault_pass" ]]; then
  echo "NOTE: $ROOT/.vault_pass exists but ansible.cfg does not use vault_password_file."
  echo "      Delete it if you want unlock to stay strictly manual: rm -f .vault_pass"
fi

echo "Wrote $VAULT_YML (encrypted)"
echo "Remember the vault password — required on every playbook run via --ask-vault-pass."
echo "Example: ansible-playbook playbooks/site.yml --ask-vault-pass"
echo "Or:      python3 scripts/render-inventory.py --spawn -- --ask-vault-pass"
