#!/usr/bin/env python3
"""Refresh Ansible inventory from OpenTofu handoff; optionally spawn playbook.

Reads:
  infra/handoff/home-lab.json
  infra/handoff/home-lab.inventory.yaml

Always overwrites (OpenTofu-derived only):
  ansible/inventories/home-lab/hosts.yaml
  ansible/inventories/home-lab/group_vars/from_opentofu.yaml  (gitignored)

Never touches group_vars/all.yaml, application.yaml, registry.yaml, playbooks,
roles, or ansible/.secrets/. Change servers via terraform.tfvars → tofu apply →
this script.

With --spawn: refresh inventory, run operator preflight (--check), then exec
ansible-playbook.
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import socket
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    yaml = None  # type: ignore


ROOT = Path(__file__).resolve().parents[2]
ANSIBLE = ROOT / "ansible"
HANDOFF_JSON = ROOT / "infra" / "handoff" / "home-lab.json"
HANDOFF_INVENTORY = ROOT / "infra" / "handoff" / "home-lab.inventory.yaml"
OUT_HOSTS = ANSIBLE / "inventories" / "home-lab" / "hosts.yaml"
OUT_VARS = ANSIBLE / "inventories" / "home-lab" / "group_vars" / "from_opentofu.yaml"
ALL_VARS = ANSIBLE / "inventories" / "home-lab" / "group_vars" / "all.yaml"
DEFAULT_PLAYBOOK = "playbooks/site.yml"
SECRETS_DIR = ANSIBLE / ".secrets"
DEPLOY_KEY = SECRETS_DIR / "flux-deploy-key"
AGE_KEY = SECRETS_DIR / "sops-age" / "age.key"

HEADER = (
    "# Generated by ansible/scripts/render-inventory.py from OpenTofu handoff.\n"
    "# Do not edit — change terraform.tfvars and re-run this script.\n"
    "# Operator settings live in group_vars/all.yaml and ansible/.secrets/.\n"
)


def fail(msg: str) -> None:
    print(f"ERROR: {msg}", file=sys.stderr)
    raise SystemExit(1)


def load_yaml(path: Path) -> dict:
    text = path.read_text(encoding="utf-8")
    if yaml is not None:
        data = yaml.safe_load(text)
        if not isinstance(data, dict):
            fail(f"{path}: expected mapping")
        return data
    fail(
        "PyYAML is required (pip install pyyaml). "
        "Alternatively ensure ansible (which vendors yaml) is installed and re-run."
    )
    return {}


def dump_yaml(data: object) -> str:
    if yaml is not None:
        return yaml.safe_dump(data, default_flow_style=False, sort_keys=False)
    fail("PyYAML is required to write inventory")
    return ""


def write_inventory_file(path: Path, content: str) -> str:
    """Always write OpenTofu-derived inventory file. Returns 'wrote' or 'refreshed'."""
    existed = path.is_file()
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return "refreshed" if existed else "wrote"


def build_payloads() -> tuple[dict, dict]:
    if not HANDOFF_JSON.is_file():
        fail(
            "infra/handoff/home-lab.json missing — "
            "run tofu apply in infra/environments/home-lab first"
        )
    if not HANDOFF_INVENTORY.is_file():
        fail(
            "infra/handoff/home-lab.inventory.yaml missing — "
            "run tofu apply in infra/environments/home-lab first"
        )

    handoff = json.loads(HANDOFF_JSON.read_text(encoding="utf-8"))
    inventory = load_yaml(HANDOFF_INVENTORY)

    ansible_inventory = handoff.get("ansible_inventory") or inventory
    if not isinstance(ansible_inventory, dict):
        fail("ansible_inventory must be a mapping")

    firewall = handoff.get("firewall") or {}
    backup = handoff.get("backup") or {}
    dns = handoff.get("dns") or {}

    admin_cidrs: list[str] = []
    if isinstance(firewall, dict):
        for rule in firewall.get("rules") or []:
            if not isinstance(rule, dict):
                continue
            purpose = str(rule.get("purpose") or "")
            cidr = rule.get("source_cidr")
            if cidr and ("ssh-admin" in str(rule.get("name") or "") or "admin" in purpose):
                if cidr not in admin_cidrs and cidr != "0.0.0.0/0":
                    admin_cidrs.append(str(cidr))

    vars_payload = {
        "opentofu_firewall_policy": firewall,
        "opentofu_backup": backup,
        "opentofu_dns": dns,
        "opentofu_admin_cidrs": admin_cidrs,
        "application_node": handoff.get("application_node"),
        "registry_node": handoff.get("registry_node"),
    }
    return ansible_inventory, vars_payload


def ensure_inventory() -> None:
    """Always refresh OpenTofu-derived inventory files from handoff."""
    ansible_inventory, vars_payload = build_payloads()

    hosts_status = write_inventory_file(
        OUT_HOSTS,
        HEADER + dump_yaml(ansible_inventory),
    )
    vars_status = write_inventory_file(
        OUT_VARS,
        HEADER + dump_yaml(vars_payload),
    )

    for file_path, status in ((OUT_HOSTS, hosts_status), (OUT_VARS, vars_status)):
        rel = file_path.relative_to(ROOT)
        print(f"{status.capitalize()} {rel}")


def _first_application_host(inventory: dict) -> tuple[str, dict] | None:
    children = (inventory.get("all") or {}).get("children") or {}
    application = children.get("application") or {}
    hosts = application.get("hosts") or {}
    if not isinstance(hosts, dict) or not hosts:
        return None
    name = next(iter(hosts))
    meta = hosts[name]
    if not isinstance(meta, dict):
        return None
    return str(name), meta


def _tcp_reachable(host: str, port: int, timeout: float = 3.0) -> bool:
    try:
        with socket.create_connection((host, port), timeout=timeout):
            return True
    except OSError:
        return False


def run_preflight(*, probe_ssh: bool = True) -> int:
    """Fail closed on missing operator gates. Returns 0 when all checks pass."""
    errors: list[str] = []
    warnings: list[str] = []

    if not OUT_HOSTS.is_file() or not OUT_VARS.is_file():
        fail(
            "inventory missing — run python3 scripts/render-inventory.py "
            "after tofu apply"
        )

    inventory = load_yaml(OUT_HOSTS)
    host_entry = _first_application_host(inventory)
    if host_entry is None:
        errors.append("hosts.yaml has no application hosts")
    else:
        name, meta = host_entry
        ansible_host = str(meta.get("ansible_host") or "")
        ansible_user = str(meta.get("ansible_user") or "")
        ansible_port = int(meta.get("ansible_port") or 22)
        print(f"CHECK host: {name} {ansible_user}@{ansible_host}:{ansible_port}")
        if not ansible_host or ansible_host in {"127.0.0.1", "0.0.0.0"}:
            errors.append(f"ansible_host looks invalid: {ansible_host!r}")
        if probe_ssh and ansible_host:
            if _tcp_reachable(ansible_host, ansible_port):
                print(f"CHECK ssh tcp: {ansible_host}:{ansible_port} reachable")
            else:
                errors.append(
                    f"SSH TCP timeout/refused for {ansible_user}@{ansible_host}:{ansible_port} "
                    f"— fix application_node in terraform.tfvars, tofu apply, "
                    f"then re-run render-inventory.py"
                )

    if not ALL_VARS.is_file():
        errors.append(f"missing {ALL_VARS.relative_to(ROOT)}")
    else:
        all_vars = load_yaml(ALL_VARS)
        flux_git_url = str(all_vars.get("flux_git_url") or "")
        auth_mode = str(all_vars.get("flux_git_auth_mode") or "ssh")
        skip_sops = bool(all_vars.get("flux_skip_sops_secret") or False)
        print(f"CHECK flux_git_url: {flux_git_url}")
        if not flux_git_url:
            errors.append("flux_git_url is empty in group_vars/all.yaml")
        elif (
            "<" in flux_git_url
            or ">" in flux_git_url
            or "example.com" in flux_git_url
        ):
            errors.append(
                "flux_git_url still has a placeholder — set the real private "
                "off-server seed/recovery remote in group_vars/all.yaml"
            )

        if auth_mode == "ssh":
            if DEPLOY_KEY.is_file():
                print(f"CHECK deploy key: {DEPLOY_KEY.relative_to(ROOT)} present")
            else:
                errors.append(
                    f"missing SSH deploy key at {DEPLOY_KEY.relative_to(ROOT)} "
                    f"(flux_git_auth_mode=ssh)"
                )
        elif auth_mode == "https":
            if str(all_vars.get("flux_https_password") or ""):
                print("CHECK https auth: flux_https_password set")
            else:
                warnings.append(
                    "flux_git_auth_mode=https but flux_https_password is empty "
                    "(may fail if remote requires auth)"
                )
        else:
            errors.append(f"unsupported flux_git_auth_mode: {auth_mode!r}")

        if skip_sops:
            print("CHECK sops age: skipped (flux_skip_sops_secret=true)")
        elif AGE_KEY.is_file():
            print(f"CHECK sops age: {AGE_KEY.relative_to(ROOT)} present")
        else:
            errors.append(
                f"missing sops age key at {AGE_KEY.relative_to(ROOT)} "
                f"(or set flux_skip_sops_secret: true)"
            )

    enc = os.environ.get("K3S_SECRETS_ENCRYPTION_KEY", "").strip()
    vault_yml = (
        ANSIBLE / "inventories" / "home-lab" / "group_vars" / "application" / "vault.yml"
    )
    vault_pass = ANSIBLE / ".vault_pass"
    if enc:
        print("CHECK encryption key: K3S_SECRETS_ENCRYPTION_KEY is set")
    elif vault_yml.is_file():
        print(f"CHECK encryption key: vault file present ({vault_yml.relative_to(ROOT)})")
        print(
            "NOTE: unlock manually with --ask-vault-pass on this local PC "
            "(ansible.cfg has no vault_password_file)"
        )
        if vault_pass.is_file():
            warnings.append(
                f"{vault_pass.relative_to(ROOT)} exists but is unused — "
                "delete it for strict manual unlock, or pass "
                "--vault-password-file explicitly if you intend unattended decrypt"
            )
    else:
        errors.append(
            "missing secrets encryption key — preferred: "
            "run scripts/init-encryption-vault.sh (interactive vault password), "
            "then playbooks with --ask-vault-pass. Fallback: export "
            'K3S_SECRETS_ENCRYPTION_KEY="$(openssl rand -base64 32)"'
        )

    for w in warnings:
        print(f"WARN: {w}")
    if errors:
        for e in errors:
            print(f"ERROR: {e}", file=sys.stderr)
        print(
            "PREFLIGHT_FAIL — fix blockers above, then re-run "
            "`python3 scripts/render-inventory.py --check`",
            file=sys.stderr,
        )
        return 1

    print("PREFLIGHT_OK")
    return 0


def spawn_playbook(playbook: str, extra_args: list[str]) -> int:
    if not OUT_HOSTS.is_file() or not OUT_VARS.is_file():
        fail(
            "inventory missing — run without --spawn first "
            "(or ensure hosts.yaml and from_opentofu.yaml exist)"
        )

    binary = shutil.which("ansible-playbook")
    if not binary:
        fail("ansible-playbook not found on PATH")

    playbook_path = Path(playbook)
    if not playbook_path.is_absolute():
        playbook_path = ANSIBLE / playbook_path
    if not playbook_path.is_file():
        fail(f"playbook not found: {playbook_path}")

    cmd = [binary, str(playbook_path), *extra_args]
    print(f"Spawning: {' '.join(cmd)} (cwd={ANSIBLE})")
    os.chdir(ANSIBLE)
    os.execv(binary, cmd)
    return 1  # pragma: no cover — execv does not return


def main() -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Always refresh OpenTofu-derived Ansible inventory "
            "(hosts.yaml + from_opentofu.yaml). Never touches all.yaml or .secrets. "
            "Use --check for operator preflight. "
            "With --spawn, refresh + preflight then launches ansible-playbook."
        )
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Deprecated no-op: refresh is always on (kept for old docs/scripts)",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help=(
            "Run fail-closed operator preflight (inventory host TCP, flux_git_url, "
            "deploy/age keys, encryption key). Does not touch all.yaml/.secrets."
        ),
    )
    parser.add_argument(
        "--skip-ssh-probe",
        action="store_true",
        help="With --check/--spawn, do not probe SSH TCP reachability",
    )
    parser.add_argument(
        "--spawn",
        nargs="?",
        const=DEFAULT_PLAYBOOK,
        default=None,
        metavar="PLAYBOOK",
        help=(
            f"After refresh + preflight, spawn ansible-playbook "
            f"(default: {DEFAULT_PLAYBOOK}). Does not touch all.yaml/.secrets."
        ),
    )
    parser.add_argument(
        "ansible_args",
        nargs=argparse.REMAINDER,
        help="Extra args after -- are passed to ansible-playbook when spawning",
    )
    args = parser.parse_args()

    extra = list(args.ansible_args or [])
    if extra and extra[0] == "--":
        extra = extra[1:]

    if args.force:
        print("NOTE: --force is obsolete; OpenTofu inventory is always refreshed")

    ensure_inventory()

    if args.check or args.spawn is not None:
        rc = run_preflight(probe_ssh=not args.skip_ssh_probe)
        if rc != 0:
            return rc

    if args.spawn is not None:
        spawn_playbook(args.spawn, extra)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
