apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-postgres-0
  namespace: identity
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: platform
    # Protected reclaim flag to prevent unintended volume pruning
    platform.nacfson.io/protection: retain-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
