apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: identity
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: platform
spec:
  type: ClusterIP
  ports:
    - name: postgresql
      port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app.kubernetes.io/name: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-headless
  namespace: identity
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: platform
spec:
  clusterIP: None
  ports:
    - name: postgresql
      port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app.kubernetes.io/name: postgres
