apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres
  namespace: identity
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: platform
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-init
  namespace: identity
  labels:
    app.kubernetes.io/name: postgres-init
    app.kubernetes.io/part-of: platform
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-backup
  namespace: identity
  labels:
    app.kubernetes.io/name: postgres-backup
    app.kubernetes.io/part-of: platform
automountServiceAccountToken: true
