apiVersion: apps/v1
kind: Deployment
metadata:
  name: pn-backend
  namespace: proj-pn
  labels:
    app.kubernetes.io/name: pn-backend
    app.kubernetes.io/part-of: project-pn
    platform.nacfson.io/managed-by: platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pn-backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pn-backend
        app.kubernetes.io/part-of: project-pn
    spec:
      serviceAccountName: pn-workload-sa
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: backend
          image: ghcr.io/nacfson/project-pn-backend@sha256:1820a01a975db1b8bf269ce737e1a3af39a056551bfdf8628ed66b95dc4374b6
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          workingDir: /app
          env:
            - name: DB_HOST
              value: "vault-db-proxy.vault.svc"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "proj_pn"
            - name: DB_USER
              value: "project:pn:workload:backend"
            - name: DB_TOKEN
              value: "project:pn:workload:backend"
            - name: MIGRATIONS_PATH
              value: "file:///app/db/migrations"
            - name: CENTRAL_AUTH_INTERNAL_URL
              value: "http://keycloak-service.identity.svc:8080/realms/platform"
            - name: CENTRAL_AUTH_URL
              value: "https://auth.example.com/realms/platform"
            - name: PORT
              value: "8080"
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: "300m"
              memory: "512Mi"
            limits:
              cpu: "300m"
              memory: "512Mi"
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: logs
              mountPath: /var/log/project-pn
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 5
      volumes:
        - name: tmp
          emptyDir: {}
        - name: logs
          emptyDir: {}
