apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: project-pn-ingress
  namespace: proj-pn
  labels:
    app.kubernetes.io/name: project-pn
    app.kubernetes.io/part-of: project-pn
spec:
  entryPoints:
    - web
    - websecure
  routes:
    # Protected Frontend & Backend Routes
    - match: Host(`pn.example.com`)
      kind: Rule
      middlewares:
        - name: strip-forged-headers
          namespace: platform
        - name: forward-auth
          namespace: platform
      services:
        - name: pn-frontend
          port: 80
    - match: Host(`pn.example.com`) && PathPrefix(`/api`)
      kind: Rule
      middlewares:
        - name: strip-forged-headers
          namespace: platform
        - name: forward-auth
          namespace: platform
      services:
        - name: pn-backend
          port: 8080
