apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    platform.processmanager.dev/unit: infrastructure
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
