apiVersion: v1
kind: ServiceAccount
metadata:
  name: keycloak
  namespace: identity
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/part-of: platform
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gateway
  namespace: identity
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/part-of: platform
automountServiceAccountToken: true
