apiVersion: v1
kind: Namespace
metadata:
  name: identity
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    app.kubernetes.io/part-of: platform
    name: identity
---
apiVersion: v1
kind: Namespace
metadata:
  name: platform
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    app.kubernetes.io/part-of: platform
    name: platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: governance
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    app.kubernetes.io/part-of: platform
    name: governance
