apiVersion: v1
kind: ServiceAccount
metadata:
  name: project-sa-template
  labels:
    app.kubernetes.io/part-of: platform
    platform.nacfson.io/managed-by: platform
automountServiceAccountToken: false
