apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vault

resources:
  - namespace.yaml
  - network-policy.yaml
  - openbao-config.yaml
  - openbao-statefulset.yaml
  - openbao-service.yaml
  - backup-cronjob.yaml
  - service-accounts.yaml
