apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-db-proxy
  namespace: vault
  labels:
    app.kubernetes.io/name: vault-db-proxy
    app.kubernetes.io/part-of: platform-vault
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-registry-proxy
  namespace: vault
  labels:
    app.kubernetes.io/name: vault-registry-proxy
    app.kubernetes.io/part-of: platform-vault
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openbao-backup
  namespace: vault
  labels:
    app.kubernetes.io/name: openbao-backup
    app.kubernetes.io/part-of: platform-vault
automountServiceAccountToken: true
