apiVersion: v1
kind: Secret
metadata:
    name: google-oidc-broker
    namespace: identity-system
type: Opaque
stringData:
    clientId: ENC[AES256_GCM,data:MUrvrLud7outGGdcyWnnm9k4OCvyZ0aoUMiWVUKozX6kr04R53gFF6e8BVNlVdKWwCM6FJ7Og9Fqw069Z+nZYLY1MazEw7J1,iv:CtOQ/KQCK+N6snDbqxFTZQKQ38SQq0MoRz4WMKfjSmA=,tag:MeZAHwVc29KRFXCTTo5U6w==,type:str]
    clientSecret: ENC[AES256_GCM,data:AZwlTbWS5xczmrXJLw9dpYg9EmDZB36F4J4+X7TCL5Fyi5M=,iv:cgqe/JapZemkgEAkjr5ND1kNCmqVOgqMqO+4H3hxDiM=,tag:6pIKRpBnUkSQukzokX7ltg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWTGtHUlJseWpTdVpUNmo0
            M2d2N1dncDc2dmpDRFY1UXlJcU9qTHdIMUdjCnFnWFBpbUpiR09WQVVWWUhxalR5
            Vmx2MUl2Mk9EdGxvWDFQQjFwZ08xTlEKLS0tIHM4RzF4OStTbDhnVFpZelFLdXZO
            Q0RVZkh1ZkJwQ3dFWUxQMktQRkxKVDgK+vQnc+DHwh3YRg6Q0swYyq8HwCaM4XQp
            pYhtMMxyqL7bvs4k48/18cvUv4ptmSLU5XjscuPgRYmN45f6WgTSdw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c47fy4esygealylpngzjnfr4hf48k6k2axre9jnnua3c0l8jdcsqkec4m6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-24T10:24:18Z"
    mac: ENC[AES256_GCM,data:t3mzJVlyS+zdbAPbbPiJpCk5Luf4f0PuyGjDKE53wnx+3yVgPYX+gIDjKzLJGMrny0DdRd6ZcuwQko8TTY/VC7vn53gGwngFto3+qNsZhWH1T0z2Lpoajb+/VBRwEY8fQesT+bDVQT6yvBW3hAvOy9onEUpOJ2Rks3ANqrNFlU4=,iv:aFOtresuwCJHhwjhpepII2le0Lx31By2ZSBYF+URTF8=,tag:qsmIoRVgisfUGTPmFCCcrw==,type:str]
    version: 3.13.3
