apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cnpg
  namespace: cnpg-system
spec:
  interval: 1h
  url: https://cloudnative-pg.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
  namespace: cnpg-system
spec:
  interval: 30m
  chart:
    spec:
      chart: cloudnative-pg
      version: "0.29.0"
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: cnpg-system
      interval: 1h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    crds:
      create: true
    image:
      repository: ghcr.io/cloudnative-pg/cloudnative-pg
      tag: "1.30.0"
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 500m
        memory: 512Mi
    config:
      data:
        INHERITED_ANNOTATIONS: platform.processmanager.dev/*
        INHERITED_LABELS: platform.processmanager.dev/*
